// GENERATED by pipeline/build_dataset.py - do not edit by hand.
// Sources: Banca d'Italia STAFINRA TFR20232 / TFR20267; Istat Frame SBS territoriale, province 2015-2020
// Negative capitalGapScore = underfinanced (financing deficit).

export const CAPITAL_META = {
  "years": [
    "2015",
    "2016",
    "2017",
    "2018",
    "2019",
    "2020"
  ],
  "provinces": [
    "Bergamo",
    "Brescia",
    "Milano",
    "Monza e della Brianza",
    "Varese"
  ],
  "sectors": [
    "Costruzioni",
    "Industria",
    "Servizi"
  ],
  "sources": {
    "credit": "Banca d'Italia STAFINRA TFR20232 / TFR20267",
    "economy": "Istat Frame SBS territoriale, province 2015-2020"
  },
  "notes": "Negative capitalGapScore = underfinanced. Deposits are province-level."
};

export const CAPITAL_DATA = [
  {
    "id": "brescia-costruzioni",
    "province": "Brescia",
    "sector": "Costruzioni",
    "economicMomentum": 68,
    "financingSupport": 40,
    "capitalGapScore": -27,
    "subScores": {
      "turnoverGrowth": 99,
      "businessGrowth": 31,
      "sectorPerformance": 64,
      "creditGrowth": 0,
      "depositStrength": 100,
      "liquidity": 52
    },
    "raw": {
      "turnoverGrowthPct": 12.32,
      "businessGrowthPct": -0.81,
      "employeeGrowthPct": 1.25,
      "creditGrowthPct": -18.0,
      "depositGrowthPct": 8.3,
      "turnoverKEUR": 5067205.0,
      "loansKEUR": 2174882.0,
      "depositsKEUR": 130190667.0,
      "businesses": 13270,
      "creditIntensityPct": 42.92
    },
    "series": [
      {
        "year": "2015",
        "turnover_kEUR": 2834932.0,
        "loans_kEUR": 5865568.0,
        "businesses": 13822
      },
      {
        "year": "2016",
        "turnover_kEUR": 4560198.0,
        "loans_kEUR": 5058196.0,
        "businesses": 13560
      },
      {
        "year": "2017",
        "turnover_kEUR": 4720639.0,
        "loans_kEUR": 4649999.0,
        "businesses": 13539
      },
      {
        "year": "2018",
        "turnover_kEUR": 4837117.0,
        "loans_kEUR": 3869532.0,
        "businesses": 13297
      },
      {
        "year": "2019",
        "turnover_kEUR": 5053960.0,
        "loans_kEUR": 2461367.0,
        "businesses": 12942
      },
      {
        "year": "2020",
        "turnover_kEUR": 5067205.0,
        "loans_kEUR": 2174882.0,
        "businesses": 13270
      }
    ]
  },
  {
    "id": "milano-costruzioni",
    "province": "Milano",
    "sector": "Costruzioni",
    "economicMomentum": 78,
    "financingSupport": 53,
    "capitalGapScore": -25,
    "subScores": {
      "turnoverGrowth": 70,
      "businessGrowth": 89,
      "sectorPerformance": 77,
      "creditGrowth": 54,
      "depositStrength": 52,
      "liquidity": 51
    },
    "raw": {
      "turnoverGrowthPct": 9.22,
      "businessGrowthPct": 0.97,
      "employeeGrowthPct": 1.71,
      "creditGrowthPct": -6.47,
      "depositGrowthPct": 7.04,
      "turnoverKEUR": 16361703.0,
      "loansKEUR": 11696323.0,
      "depositsKEUR": 692996322.0,
      "businesses": 27348,
      "creditIntensityPct": 71.49
    },
    "series": [
      {
        "year": "2015",
        "turnover_kEUR": 10527740.0,
        "loans_kEUR": 16339773.0,
        "businesses": 26054
      },
      {
        "year": "2016",
        "turnover_kEUR": 14750202.0,
        "loans_kEUR": 15110625.0,
        "businesses": 26318
      },
      {
        "year": "2017",
        "turnover_kEUR": 15165997.0,
        "loans_kEUR": 13214423.0,
        "businesses": 26531
      },
      {
        "year": "2018",
        "turnover_kEUR": 15566999.0,
        "loans_kEUR": 12402469.0,
        "businesses": 26365
      },
      {
        "year": "2019",
        "turnover_kEUR": 14738876.0,
        "loans_kEUR": 11255418.0,
        "businesses": 26653
      },
      {
        "year": "2020",
        "turnover_kEUR": 16361703.0,
        "loans_kEUR": 11696323.0,
        "businesses": 27348
      }
    ]
  },
  {
    "id": "monza-e-della-brianza-servizi",
    "province": "Monza e della Brianza",
    "sector": "Servizi",
    "economicMomentum": 87,
    "financingSupport": 64,
    "capitalGapScore": -24,
    "subScores": {
      "turnoverGrowth": 71,
      "businessGrowth": 95,
      "sectorPerformance": 100,
      "creditGrowth": 74,
      "depositStrength": 84,
      "liquidity": 5
    },
    "raw": {
      "turnoverGrowthPct": 9.39,
      "businessGrowthPct": 1.14,
      "employeeGrowthPct": 2.48,
      "creditGrowthPct": -2.1,
      "depositGrowthPct": 7.9,
      "turnoverKEUR": 31953411.0,
      "loansKEUR": 5749391.0,
      "depositsKEUR": 87152477.0,
      "businesses": 55713,
      "creditIntensityPct": 17.99
    },
    "series": [
      {
        "year": "2015",
        "turnover_kEUR": 20400744.0,
        "loans_kEUR": 6393379.0,
        "businesses": 52632
      },
      {
        "year": "2016",
        "turnover_kEUR": 28825269.0,
        "loans_kEUR": 6256358.0,
        "businesses": 53499
      },
      {
        "year": "2017",
        "turnover_kEUR": 30270177.0,
        "loans_kEUR": 6031785.0,
        "businesses": 54912
      },
      {
        "year": "2018",
        "turnover_kEUR": 31171895.0,
        "loans_kEUR": 5773677.0,
        "businesses": 55222
      },
      {
        "year": "2019",
        "turnover_kEUR": 32491950.0,
        "loans_kEUR": 5546544.0,
        "businesses": 54610
      },
      {
        "year": "2020",
        "turnover_kEUR": 31953411.0,
        "loans_kEUR": 5749391.0,
        "businesses": 55713
      }
    ]
  },
  {
    "id": "bergamo-costruzioni",
    "province": "Bergamo",
    "sector": "Costruzioni",
    "economicMomentum": 55,
    "financingSupport": 37,
    "capitalGapScore": -18,
    "subScores": {
      "turnoverGrowth": 100,
      "businessGrowth": 19,
      "sectorPerformance": 30,
      "creditGrowth": 28,
      "depositStrength": 52,
      "liquidity": 38
    },
    "raw": {
      "turnoverGrowthPct": 12.46,
      "businessGrowthPct": -1.15,
      "employeeGrowthPct": 0.12,
      "creditGrowthPct": -12.02,
      "depositGrowthPct": 7.06,
      "turnoverKEUR": 5799719.0,
      "loansKEUR": 2357209.0,
      "depositsKEUR": 109453383.0,
      "businesses": 14472,
      "creditIntensityPct": 40.64
    },
    "series": [
      {
        "year": "2015",
        "turnover_kEUR": 3223604.0,
        "loans_kEUR": 4472132.0,
        "businesses": 15335
      },
      {
        "year": "2016",
        "turnover_kEUR": 5267640.0,
        "loans_kEUR": 4006928.0,
        "businesses": 15100
      },
      {
        "year": "2017",
        "turnover_kEUR": 5444179.0,
        "loans_kEUR": 3407361.0,
        "businesses": 15082
      },
      {
        "year": "2018",
        "turnover_kEUR": 5851667.0,
        "loans_kEUR": 2824800.0,
        "businesses": 14681
      },
      {
        "year": "2019",
        "turnover_kEUR": 6072338.0,
        "loans_kEUR": 2434689.0,
        "businesses": 14208
      },
      {
        "year": "2020",
        "turnover_kEUR": 5799719.0,
        "loans_kEUR": 2357209.0,
        "businesses": 14472
      }
    ]
  },
  {
    "id": "bergamo-servizi",
    "province": "Bergamo",
    "sector": "Servizi",
    "economicMomentum": 69,
    "financingSupport": 52,
    "capitalGapScore": -17,
    "subScores": {
      "turnoverGrowth": 48,
      "businessGrowth": 89,
      "sectorPerformance": 76,
      "creditGrowth": 70,
      "depositStrength": 52,
      "liquidity": 4
    },
    "raw": {
      "turnoverGrowthPct": 6.89,
      "businessGrowthPct": 0.95,
      "employeeGrowthPct": 1.66,
      "creditGrowthPct": -3.0,
      "depositGrowthPct": 7.06,
      "turnoverKEUR": 28314490.0,
      "loansKEUR": 7676682.0,
      "depositsKEUR": 109453383.0,
      "businesses": 65875,
      "creditIntensityPct": 27.11
    },
    "series": [
      {
        "year": "2015",
        "turnover_kEUR": 20292187.0,
        "loans_kEUR": 8939443.0,
        "businesses": 62826
      },
      {
        "year": "2016",
        "turnover_kEUR": 28675060.0,
        "loans_kEUR": 9137020.0,
        "businesses": 63277
      },
      {
        "year": "2017",
        "turnover_kEUR": 29392598.0,
        "loans_kEUR": 8833766.0,
        "businesses": 64679
      },
      {
        "year": "2018",
        "turnover_kEUR": 30983968.0,
        "loans_kEUR": 8149484.0,
        "businesses": 65032
      },
      {
        "year": "2019",
        "turnover_kEUR": 31616163.0,
        "loans_kEUR": 7466982.0,
        "businesses": 63572
      },
      {
        "year": "2020",
        "turnover_kEUR": 28314490.0,
        "loans_kEUR": 7676682.0,
        "businesses": 65875
      }
    ]
  },
  {
    "id": "milano-servizi",
    "province": "Milano",
    "sector": "Servizi",
    "economicMomentum": 72,
    "financingSupport": 59,
    "capitalGapScore": -13,
    "subScores": {
      "turnoverGrowth": 44,
      "businessGrowth": 100,
      "sectorPerformance": 82,
      "creditGrowth": 87,
      "depositStrength": 52,
      "liquidity": 0
    },
    "raw": {
      "turnoverGrowthPct": 6.45,
      "businessGrowthPct": 1.3,
      "employeeGrowthPct": 1.87,
      "creditGrowthPct": 0.72,
      "depositGrowthPct": 7.04,
      "turnoverKEUR": 286004820.0,
      "loansKEUR": 68678132.0,
      "depositsKEUR": 692996322.0,
      "businesses": 282561,
      "creditIntensityPct": 24.01
    },
    "series": [
      {
        "year": "2015",
        "turnover_kEUR": 209220404.0,
        "loans_kEUR": 66259783.0,
        "businesses": 264872
      },
      {
        "year": "2016",
        "turnover_kEUR": 274509075.0,
        "loans_kEUR": 69975297.0,
        "businesses": 268571
      },
      {
        "year": "2017",
        "turnover_kEUR": 295671104.0,
        "loans_kEUR": 69340108.0,
        "businesses": 275313
      },
      {
        "year": "2018",
        "turnover_kEUR": 303647541.0,
        "loans_kEUR": 66984057.0,
        "businesses": 280224
      },
      {
        "year": "2019",
        "turnover_kEUR": 307929115.0,
        "loans_kEUR": 62072081.0,
        "businesses": 278416
      },
      {
        "year": "2020",
        "turnover_kEUR": 286004820.0,
        "loans_kEUR": 68678132.0,
        "businesses": 282561
      }
    ]
  },
  {
    "id": "varese-servizi",
    "province": "Varese",
    "sector": "Servizi",
    "economicMomentum": 51,
    "financingSupport": 40,
    "capitalGapScore": -11,
    "subScores": {
      "turnoverGrowth": 24,
      "businessGrowth": 75,
      "sectorPerformance": 63,
      "creditGrowth": 77,
      "depositStrength": 0,
      "liquidity": 9
    },
    "raw": {
      "turnoverGrowthPct": 4.29,
      "businessGrowthPct": 0.54,
      "employeeGrowthPct": 1.23,
      "creditGrowthPct": -1.46,
      "depositGrowthPct": 5.7,
      "turnoverKEUR": 20412830.0,
      "loansKEUR": 4069182.0,
      "depositsKEUR": 75822966.0,
      "businesses": 51463,
      "creditIntensityPct": 19.93
    },
    "series": [
      {
        "year": "2015",
        "turnover_kEUR": 16548827.0,
        "loans_kEUR": 4380189.0,
        "businesses": 50092
      },
      {
        "year": "2016",
        "turnover_kEUR": 22454906.0,
        "loans_kEUR": 4387375.0,
        "businesses": 50523
      },
      {
        "year": "2017",
        "turnover_kEUR": 23620434.0,
        "loans_kEUR": 4103437.0,
        "businesses": 51405
      },
      {
        "year": "2018",
        "turnover_kEUR": 24557881.0,
        "loans_kEUR": 4023230.0,
        "businesses": 51300
      },
      {
        "year": "2019",
        "turnover_kEUR": 25001742.0,
        "loans_kEUR": 3934652.0,
        "businesses": 50079
      },
      {
        "year": "2020",
        "turnover_kEUR": 20412830.0,
        "loans_kEUR": 4069182.0,
        "businesses": 51463
      }
    ]
  },
  {
    "id": "varese-costruzioni",
    "province": "Varese",
    "sector": "Costruzioni",
    "economicMomentum": 38,
    "financingSupport": 31,
    "capitalGapScore": -7,
    "subScores": {
      "turnoverGrowth": 61,
      "businessGrowth": 44,
      "sectorPerformance": 0,
      "creditGrowth": 22,
      "depositStrength": 0,
      "liquidity": 100
    },
    "raw": {
      "turnoverGrowthPct": 8.3,
      "businessGrowthPct": -0.39,
      "employeeGrowthPct": -0.91,
      "creditGrowthPct": -13.36,
      "depositGrowthPct": 5.7,
      "turnoverKEUR": 2007350.0,
      "loansKEUR": 716546.0,
      "depositsKEUR": 75822966.0,
      "businesses": 8345,
      "creditIntensityPct": 35.7
    },
    "series": [
      {
        "year": "2015",
        "turnover_kEUR": 1347176.0,
        "loans_kEUR": 1467609.0,
        "businesses": 8511
      },
      {
        "year": "2016",
        "turnover_kEUR": 2080975.0,
        "loans_kEUR": 1401178.0,
        "businesses": 8489
      },
      {
        "year": "2017",
        "turnover_kEUR": 2031517.0,
        "loans_kEUR": 1139158.0,
        "businesses": 8439
      },
      {
        "year": "2018",
        "turnover_kEUR": 2101890.0,
        "loans_kEUR": 910269.0,
        "businesses": 8291
      },
      {
        "year": "2019",
        "turnover_kEUR": 2097045.0,
        "loans_kEUR": 775099.0,
        "businesses": 8118
      },
      {
        "year": "2020",
        "turnover_kEUR": 2007350.0,
        "loans_kEUR": 716546.0,
        "businesses": 8345
      }
    ]
  },
  {
    "id": "brescia-servizi",
    "province": "Brescia",
    "sector": "Servizi",
    "economicMomentum": 64,
    "financingSupport": 60,
    "capitalGapScore": -4,
    "subScores": {
      "turnoverGrowth": 45,
      "businessGrowth": 86,
      "sectorPerformance": 68,
      "creditGrowth": 59,
      "depositStrength": 100,
      "liquidity": 3
    },
    "raw": {
      "turnoverGrowthPct": 6.6,
      "businessGrowthPct": 0.88,
      "employeeGrowthPct": 1.39,
      "creditGrowthPct": -5.41,
      "depositGrowthPct": 8.3,
      "turnoverKEUR": 34784106.0,
      "loansKEUR": 9704012.0,
      "depositsKEUR": 130190667.0,
      "businesses": 80925,
      "creditIntensityPct": 27.9
    },
    "series": [
      {
        "year": "2015",
        "turnover_kEUR": 25274352.0,
        "loans_kEUR": 12812891.0,
        "businesses": 77470
      },
      {
        "year": "2016",
        "turnover_kEUR": 35257450.0,
        "loans_kEUR": 12729538.0,
        "businesses": 78126
      },
      {
        "year": "2017",
        "turnover_kEUR": 37575365.0,
        "loans_kEUR": 12267065.0,
        "businesses": 80090
      },
      {
        "year": "2018",
        "turnover_kEUR": 39041731.0,
        "loans_kEUR": 11053525.0,
        "businesses": 80581
      },
      {
        "year": "2019",
        "turnover_kEUR": 39067661.0,
        "loans_kEUR": 9865938.0,
        "businesses": 78214
      },
      {
        "year": "2020",
        "turnover_kEUR": 34784106.0,
        "loans_kEUR": 9704012.0,
        "businesses": 80925
      }
    ]
  },
  {
    "id": "monza-e-della-brianza-costruzioni",
    "province": "Monza e della Brianza",
    "sector": "Costruzioni",
    "economicMomentum": 37,
    "financingSupport": 47,
    "capitalGapScore": 9,
    "subScores": {
      "turnoverGrowth": 36,
      "businessGrowth": 64,
      "sectorPerformance": 13,
      "creditGrowth": 17,
      "depositStrength": 84,
      "liquidity": 65
    },
    "raw": {
      "turnoverGrowthPct": 5.54,
      "businessGrowthPct": 0.22,
      "employeeGrowthPct": -0.48,
      "creditGrowthPct": -14.46,
      "depositGrowthPct": 7.9,
      "turnoverKEUR": 2548635.0,
      "loansKEUR": 1207762.0,
      "depositsKEUR": 87152477.0,
      "businesses": 9050,
      "creditIntensityPct": 47.39
    },
    "series": [
      {
        "year": "2015",
        "turnover_kEUR": 1946039.0,
        "loans_kEUR": 2636673.0,
        "businesses": 8953
      },
      {
        "year": "2016",
        "turnover_kEUR": 2763637.0,
        "loans_kEUR": 2361218.0,
        "businesses": 8993
      },
      {
        "year": "2017",
        "turnover_kEUR": 2767728.0,
        "loans_kEUR": 2074387.0,
        "businesses": 9017
      },
      {
        "year": "2018",
        "turnover_kEUR": 2829702.0,
        "loans_kEUR": 1583418.0,
        "businesses": 8882
      },
      {
        "year": "2019",
        "turnover_kEUR": 2578548.0,
        "loans_kEUR": 1281566.0,
        "businesses": 8776
      },
      {
        "year": "2020",
        "turnover_kEUR": 2548635.0,
        "loans_kEUR": 1207762.0,
        "businesses": 9050
      }
    ]
  },
  {
    "id": "bergamo-industria",
    "province": "Bergamo",
    "sector": "Industria",
    "economicMomentum": 40,
    "financingSupport": 55,
    "capitalGapScore": 15,
    "subScores": {
      "turnoverGrowth": 40,
      "businessGrowth": 30,
      "sectorPerformance": 52,
      "creditGrowth": 78,
      "depositStrength": 52,
      "liquidity": 4
    },
    "raw": {
      "turnoverGrowthPct": 5.96,
      "businessGrowthPct": -0.84,
      "employeeGrowthPct": 0.86,
      "creditGrowthPct": -1.33,
      "depositGrowthPct": 7.06,
      "turnoverKEUR": 33042162.0,
      "loansKEUR": 7896435.0,
      "depositsKEUR": 109453383.0,
      "businesses": 10964,
      "creditIntensityPct": 23.9
    },
    "series": [
      {
        "year": "2015",
        "turnover_kEUR": 24732725.0,
        "loans_kEUR": 8444565.0,
        "businesses": 11436
      },
      {
        "year": "2016",
        "turnover_kEUR": 35579200.0,
        "loans_kEUR": 7935519.0,
        "businesses": 11311
      },
      {
        "year": "2017",
        "turnover_kEUR": 35660051.0,
        "loans_kEUR": 7910779.0,
        "businesses": 11440
      },
      {
        "year": "2018",
        "turnover_kEUR": 36936495.0,
        "loans_kEUR": 7742629.0,
        "businesses": 11111
      },
      {
        "year": "2019",
        "turnover_kEUR": 36800626.0,
        "loans_kEUR": 7444197.0,
        "businesses": 10977
      },
      {
        "year": "2020",
        "turnover_kEUR": 33042162.0,
        "loans_kEUR": 7896435.0,
        "businesses": 10964
      }
    ]
  },
  {
    "id": "brescia-industria",
    "province": "Brescia",
    "sector": "Industria",
    "economicMomentum": 43,
    "financingSupport": 71,
    "capitalGapScore": 28,
    "subScores": {
      "turnoverGrowth": 51,
      "businessGrowth": 25,
      "sectorPerformance": 49,
      "creditGrowth": 81,
      "depositStrength": 100,
      "liquidity": 1
    },
    "raw": {
      "turnoverGrowthPct": 7.18,
      "businessGrowthPct": -0.98,
      "employeeGrowthPct": 0.76,
      "creditGrowthPct": -0.72,
      "depositGrowthPct": 8.3,
      "turnoverKEUR": 43941889.0,
      "loansKEUR": 11355955.0,
      "depositsKEUR": 130190667.0,
      "businesses": 14032,
      "creditIntensityPct": 25.84
    },
    "series": [
      {
        "year": "2015",
        "turnover_kEUR": 31073529.0,
        "loans_kEUR": 11773716.0,
        "businesses": 14740
      },
      {
        "year": "2016",
        "turnover_kEUR": 41560844.0,
        "loans_kEUR": 11537385.0,
        "businesses": 14523
      },
      {
        "year": "2017",
        "turnover_kEUR": 44707533.0,
        "loans_kEUR": 11310467.0,
        "businesses": 14576
      },
      {
        "year": "2018",
        "turnover_kEUR": 47939961.0,
        "loans_kEUR": 11091355.0,
        "businesses": 14357
      },
      {
        "year": "2019",
        "turnover_kEUR": 48869249.0,
        "loans_kEUR": 10571213.0,
        "businesses": 14175
      },
      {
        "year": "2020",
        "turnover_kEUR": 43941889.0,
        "loans_kEUR": 11355955.0,
        "businesses": 14032
      }
    ]
  },
  {
    "id": "varese-industria",
    "province": "Varese",
    "sector": "Industria",
    "economicMomentum": 13,
    "financingSupport": 42,
    "capitalGapScore": 29,
    "subScores": {
      "turnoverGrowth": 24,
      "businessGrowth": 2,
      "sectorPerformance": 9,
      "creditGrowth": 80,
      "depositStrength": 0,
      "liquidity": 11
    },
    "raw": {
      "turnoverGrowthPct": 4.32,
      "businessGrowthPct": -1.67,
      "employeeGrowthPct": -0.62,
      "creditGrowthPct": -0.96,
      "depositGrowthPct": 5.7,
      "turnoverKEUR": 20220261.0,
      "loansKEUR": 3730197.0,
      "depositsKEUR": 75822966.0,
      "businesses": 7904,
      "creditIntensityPct": 18.45
    },
    "series": [
      {
        "year": "2015",
        "turnover_kEUR": 16368748.0,
        "loans_kEUR": 3914125.0,
        "businesses": 8598
      },
      {
        "year": "2016",
        "turnover_kEUR": 21613814.0,
        "loans_kEUR": 3846101.0,
        "businesses": 8431
      },
      {
        "year": "2017",
        "turnover_kEUR": 21040964.0,
        "loans_kEUR": 3812603.0,
        "businesses": 8413
      },
      {
        "year": "2018",
        "turnover_kEUR": 22260520.0,
        "loans_kEUR": 3709898.0,
        "businesses": 8221
      },
      {
        "year": "2019",
        "turnover_kEUR": 21899689.0,
        "loans_kEUR": 3488012.0,
        "businesses": 8040
      },
      {
        "year": "2020",
        "turnover_kEUR": 20220261.0,
        "loans_kEUR": 3730197.0,
        "businesses": 7904
      }
    ]
  },
  {
    "id": "milano-industria",
    "province": "Milano",
    "sector": "Industria",
    "economicMomentum": 20,
    "financingSupport": 62,
    "capitalGapScore": 42,
    "subScores": {
      "turnoverGrowth": 0,
      "businessGrowth": 30,
      "sectorPerformance": 37,
      "creditGrowth": 88,
      "depositStrength": 52,
      "liquidity": 15
    },
    "raw": {
      "turnoverGrowthPct": 1.72,
      "businessGrowthPct": -0.83,
      "employeeGrowthPct": 0.33,
      "creditGrowthPct": 0.8,
      "depositGrowthPct": 7.04,
      "turnoverKEUR": 100722725.0,
      "loansKEUR": 28081624.0,
      "depositsKEUR": 692996322.0,
      "businesses": 25011,
      "creditIntensityPct": 27.88
    },
    "series": [
      {
        "year": "2015",
        "turnover_kEUR": 92508935.0,
        "loans_kEUR": 26988582.0,
        "businesses": 26073
      },
      {
        "year": "2016",
        "turnover_kEUR": 109664566.0,
        "loans_kEUR": 28327598.0,
        "businesses": 25831
      },
      {
        "year": "2017",
        "turnover_kEUR": 114062987.0,
        "loans_kEUR": 27517305.0,
        "businesses": 26100
      },
      {
        "year": "2018",
        "turnover_kEUR": 122431015.0,
        "loans_kEUR": 27606531.0,
        "businesses": 25726
      },
      {
        "year": "2019",
        "turnover_kEUR": 117740579.0,
        "loans_kEUR": 26404921.0,
        "businesses": 25355
      },
      {
        "year": "2020",
        "turnover_kEUR": 100722725.0,
        "loans_kEUR": 28081624.0,
        "businesses": 25011
      }
    ]
  },
  {
    "id": "monza-e-della-brianza-industria",
    "province": "Monza e della Brianza",
    "sector": "Industria",
    "economicMomentum": 17,
    "financingSupport": 77,
    "capitalGapScore": 60,
    "subScores": {
      "turnoverGrowth": 34,
      "businessGrowth": 0,
      "sectorPerformance": 12,
      "creditGrowth": 100,
      "depositStrength": 84,
      "liquidity": 8
    },
    "raw": {
      "turnoverGrowthPct": 5.42,
      "businessGrowthPct": -1.74,
      "employeeGrowthPct": -0.51,
      "creditGrowthPct": 3.42,
      "depositGrowthPct": 7.9,
      "turnoverKEUR": 17381229.0,
      "loansKEUR": 4818705.0,
      "depositsKEUR": 87152477.0,
      "businesses": 8467,
      "creditIntensityPct": 27.72
    },
    "series": [
      {
        "year": "2015",
        "turnover_kEUR": 13349089.0,
        "loans_kEUR": 4073159.0,
        "businesses": 9246
      },
      {
        "year": "2016",
        "turnover_kEUR": 19771048.0,
        "loans_kEUR": 4273598.0,
        "businesses": 9052
      },
      {
        "year": "2017",
        "turnover_kEUR": 21733248.0,
        "loans_kEUR": 4641278.0,
        "businesses": 9138
      },
      {
        "year": "2018",
        "turnover_kEUR": 20946649.0,
        "loans_kEUR": 4396141.0,
        "businesses": 8844
      },
      {
        "year": "2019",
        "turnover_kEUR": 21640392.0,
        "loans_kEUR": 4860604.0,
        "businesses": 8601
      },
      {
        "year": "2020",
        "turnover_kEUR": 17381229.0,
        "loans_kEUR": 4818705.0,
        "businesses": 8467
      }
    ]
  }
];
